### ISSUE TITLE
Is this code repository for your paper(Topology-preserving Deep Image Segmentation) ?

### ISSUE THREAD

**Issue by o0t1ng0o** [HuXiaoling/imageSeg-2.5D_topo#1]
Hi Hu,

I have read your paper (Topology-preserving Deep Image Segmentation).
I really appreciate your work.
Is this code repository for your paper?

Many thanks!

**Comment by HuXiaoling** [comment]
The original paper only deals with 2D images, while this repository contains both 2D and 2.5D implementations (backbone may be slightly different). And we also plan to release the code for true 3D implementations (the paper is in preparation). 

I apologize for the possible confusion. But stay tuned. All of the related repositories are under construction. You can definitely adopt existing repositories regarding your own data. If there are any questions, please feel easy to post them here:)

**Comment by o0t1ng0o** [comment]
Thank you for your sharing!!!!
I will try to use this respository for 2D image.  :)
