### ISSUE TITLE
Have problem in reading topoloss.py

### ISSUE THREAD

**Issue by tanjia123456** [HuXiaoling/imageSeg-2.5D_topo#10]
Hello, thank you for your works!
can you write some comments on the Topoloss.py file? Since I am not very familiar with the calculation of PH, I hope you can write some notes.

**Comment by HuXiaoling** [comment]
I'll try to write some notes to make it more readble. Thanks for your feedback.

**Comment by HuXiaoling** [comment]
Now you could refer to this updated version: https://github.com/HuXiaoling/TopoLoss/blob/master/topoloss_pytorch.py. It should be more clear.
