### ISSUE TITLE
How to get PersistencePython.so ??

### ISSUE THREAD

**Issue by o0t1ng0o** [HuXiaoling/imageSeg-2.5D_topo#2]
https://github.com/HuXiaoling/imageSeg-3D_topo/blob/01464f17682a2a14f938116d4724dc9002375e8f/TDFMain_pytorch.py#L6

Hi, @HuXiaoling 
I  found that it import PersistencePython. But it seems that it need to recompile PersistencePython.so?
How can I recompile this file? Could you please give me some details?
Many thanks!

**Comment by HuXiaoling** [comment]
Yes. It may need to recompile PersistencePython.so because of different platform/python version. 

Please refer to https://github.com/HuXiaoling/TopoLoss. 

> Code/cPers/cPers/compile_pers_lib.sh: script to compile the library.

Be careful with your python version.
