### ISSUE TITLE
Python doesn't recognize .so file

### ISSUE THREAD

**Issue by lotem-manassen** [HuXiaoling/imageSeg-2.5D_topo#4]
Hi,
I tried to use your example, but it seems that PersistencePython.so isn't recognized:
![image](https://user-images.githubusercontent.com/55443094/89296621-407d0000-d66b-11ea-961f-72a830cda859.png)

Maybe you know how to import this .so file?

Thanks!

**Comment by HuXiaoling** [comment]
Hi @lotem-manassen, 

Could you please refer to https://github.com/HuXiaoling/imageSeg-2.5D_topo/issues/2? Hope this solves your problem.

If you still come across any problems, please feel free to post them here.
