### ISSUE TITLE
where is the "train-labels_thin.tif"

### ISSUE THREAD

**Issue by amiltonwong** [HuXiaoling/imageSeg-2.5D_topo#7]
Hi, @HuXiaoling ,

When running main.py, this [line](https://github.com/HuXiaoling/imageSeg-2.5D_topo/blob/master/util3d.py#L140), requires the file "train-labels_thin.tif". Where could we download it?

Thanks!

**Comment by HuXiaoling** [comment]
Hi @amiltonwong, sorry that I didn't provide a specific dataset here as it could be any possible 3D dataset.
